### ISSUE TITLE
--minTriples does not seem to be working.

### ISSUE THREAD

**Issue by valentin0h** [LOD-Laundromat/Frank#13]
Hi, 

I am trying Frank on Mac and the following seems always to get the same value,47.

`./frank documents --namespace foaf: --minTriples 1| wc -l`
`./frank documents --namespace foaf: --minTriples 100 | wc -l` 
`./frank documents --namespace foaf: --minTriples 10000 | wc -l`
`./frank documents --namespace foaf: --minTriples 1000000 | wc -l`
`./frank documents --namespace foaf: --minTriples 100000000 | wc -l`

On the other hand, --maxTriples seems to be working fine. 

Is this a bug, or am I missing something?

**Comment by LaurensRietveld** [comment]
A bit of both: you might have missed the error message `Could not find prefix IRI for foaf:. Using foaf: as filter`. I've improved this error msg now (and styled these error msgs in red). 
Now, the error message reads: `Could not find prefix IRI for namespace name "foaf:". Instead, filtering for documents that contain IRIs that start with "<foaf:"`
I.e., to fix your results, run a command like this: `./frank documents --namespace foaf --minTriples 1| wc -l` (minus the colon)

**Comment by LaurensRietveld** [comment]
I was a bit too quick to respond, as I didn't fix the actual error (the minTriples value being ignored). This  is fixed now as well.
