### ISSUE TITLE
head: illegal line count -- -1

### ISSUE THREAD

**Issue by jindrichmynarz** [LOD-Laundromat/Frank#15]
`head -n-1` in the `frank` script is reported as `head: illegal line count -- -1` on my system (OSX, `BASH_VERSION=3.2.57(1)-release`).

Is that a Bash version problem? Is `head -n-1` the same as `tail -n+2` (using `tail` seems to make `frank` work)?

**Comment by LaurensRietveld** [comment]
Ah, you're right, this seems to be a bash version issue. I've resolved to using sed for this particular command instead
