### ISSUE TITLE
Frank statements does not filter Frank documents

### ISSUE THREAD

**Issue by wouterbeek** [LOD-Laundromat/Frank#8]
I was expecting the following to enumerate all and only warnings in LOD documents whose size belongs to the range [100M,200M].

``` bash
./frank documents --minTriples 100000000 --maxTriples 200000000 -r | ./frank statements --predicate http://lodlaundromat.org/ontology/warning
```

**Comment by LaurensRietveld** [comment]
Don't get it. What goes wrong here? There is no document with this given predicate (see http://index.lodlaundromat.org/r2d/http%3A%2F%2Flodlaundromat.org%2Fontology%2Fwarning)

**Comment by wouterbeek** [comment]
Woops, my bad!
